/*******************************************************************************
 * File: InterceptorOverviewPanel.java
 * Description:
 *
 ******************************************************************************/
package mdscssRoot;


public class InterceptorOverviewPanel extends javax.swing.JPanel 
{

    /***************************************************************************
     * InterceptorOverviewPanel
     * 
     * Constructor
     **************************************************************************/
    public InterceptorOverviewPanel() 
    {
        initComponents();
        
        tableScrollPane.getViewport().setBackground(new java.awt.Color(27,161,226));
    }

    /***************************************************************************
     * initComponents
     * 
     * Creates and draws the container's swing components.  Autogenerated by
     * Netbeans IDE GUI Editor
     **************************************************************************/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTable = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        tblInterceptors = new javax.swing.JTable();

        setBackground(new java.awt.Color(27, 161, 226));
        setMaximumSize(new java.awt.Dimension(622, 299));
        setMinimumSize(new java.awt.Dimension(622, 299));
        setPreferredSize(new java.awt.Dimension(622, 299));

        lblTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTable.setForeground(new java.awt.Color(255, 255, 255));
        lblTable.setText("Interceptor Overview:");

        tableScrollPane.setBackground(new java.awt.Color(255, 204, 204));
        tableScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 161, 226)));
        tableScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        tableScrollPane.setOpaque(false);

        tblInterceptors.setBackground(java.awt.SystemColor.controlHighlight);
        tblInterceptors.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 161, 226)));
        tblInterceptors.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblInterceptors.setForeground(new java.awt.Color(65, 65, 65));
        tblInterceptors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Interceptor ID", "Interceptor State", "Assigned Threat", "Position (m)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInterceptors.setGridColor(new java.awt.Color(27, 161, 226));
        tblInterceptors.setIntercellSpacing(new java.awt.Dimension(5, 15));
        tblInterceptors.setOpaque(false);
        tblInterceptors.setRowHeight(45);
        tblInterceptors.setSelectionBackground(new java.awt.Color(27, 161, 226));
        tableScrollPane.setViewportView(tblInterceptors);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTable)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable tblInterceptors;
    // End of variables declaration//GEN-END:variables
}
