/*******************************************************************************
 * File: SMCDWrapper.java
 * Description:
 *
 ******************************************************************************/
package mdscssRoot;


public class SMCDWrapper extends javax.swing.JFrame 
{
    SMCDPanel mParent;
    
    /***************************************************************************
     * SMCDPanel
     * 
     * Constructor
     **************************************************************************/
    public SMCDWrapper(String pID, SMCDPanel pParent) 
    {
        this.setTitle("SMCD -- " + pID);
        
        initComponents();
        
        sMCDPanel1.setDisplayedInterceptor(pID);
        sMCDPanel1.hideExpandControls();
        
    }

    /***************************************************************************
     * initComponents
     * 
     * Creates and draws the container's swing components.  Autogenerated by
     * Netbeans IDE GUI Editor
     **************************************************************************/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sMCDPanel1 = new mdscssRoot.SMCDPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(347, 599));
        setMinimumSize(new java.awt.Dimension(347, 599));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sMCDPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sMCDPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mdscssRoot.SMCDPanel sMCDPanel1;
    // End of variables declaration//GEN-END:variables
}
